version: '3.8'

services:
  # Exemplo de um serviço web simples
  web:
    image: nginx:latest
    container_name: pluck-media-server_web
    restart: unless-stopped
    ports:
      - "80:80" # Mapeia a porta 80 do container para a porta 80 do host (se o 'port' estiver definido no umbrel-app.yml)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro

  # Exemplo de um serviço de banco de dados (se necessário)
  db:
    image: postgres:13
    container_name: pluck-media-server_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pluck_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: # Define o volume para persistência de dados do banco de dados, teste